---
version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: C:\Users\Derek\AppData\Local\FoundryVTT
        target: /data
    environment:
      # - FOUNDRY_PASSWORD=<your_password>
      # - FOUNDRY_USERNAME=<your_username>
      # - FOUNDRY_ADMIN_KEY=atropos
      - CONTAINER_CACHE=/data/container_cache
      # - CONTAINER_PATCHES=/data/container_patches
      # - CONTAINER_PATCH_URLS=
      #   https://raw.githubusercontent.com/felddy/...
      #   https://raw.githubusercontent.com/felddy/...
      # - CONTAINER_PRESERVE_CONFIG=false
      - CONTAINER_VERBOSE=false
      # - FOUNDRY_AWS_CONFIG=
      # - FOUNDRY_GID=foundry
      # - FOUNDRY_HOSTNAME=
      # - FOUNDRY_LANGUAGE=
      # - FOUNDRY_LICENSE_KEY=
      - FOUNDRY_MINIFY_STATIC_FILES=true
      # - FOUNDRY_PROXY_PORT=
      # - FOUNDRY_PROXY_SSL=false
      # - FOUNDRY_RELEASE_URL=
      # - FOUNDRY_ROUTE_PREFIX=
      # - FOUNDRY_SSL_CERT=localhost.cert
      # - FOUNDRY_SSL_KEY=localhost.key
      # - |
      #   FOUNDRY_TURN_CONFIGS=[{
      #   "url": "turn:example.com:3478",
      #   "urls": ["turn:example.com:3478", "turns:example.com:5349"],
      #   "username": "my username",
      #   "credential": "my password"
      #   }]
      # - FOUNDRY_UID=foundry
      - FOUNDRY_UPNP=true
      # - FOUNDRY_VERSION=0.7.9
      - FOUNDRY_WORLD=fallen
      # - TIMEZONE=US/Eastern
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
        mode: host
    secrets:
    - source: config_json
      target: config.json
